### ISSUE TITLE
Usuário "editor" não consegue editar tradução de mapas

### ISSUE THREAD

**Issue by leopiccionia** [InfoAmazonia/jeo-plugin#434]
Um usuário só consegue traduzir mapas e storymaps com auxílio do WPML se tiver o papel "admin". Esta função deveria estar disponível para usuários de outros níveis – "editor" no mínimo.

**Comment by leopiccionia** [comment]
Não consegui reproduzir.

Testei:
1. adicionar tradução de mapa;
2. editar tradução de mapa (tanto existente quanto criado no item anterior);
3. adicionar tradução de storymap;
4. editar tradução de storymap;
5. tornar um editor tradutor (pela aba "Translators" do WPML)

E todas as ações foram bem-sucedidas.

**Comment by marinarcruz** [comment]
Adicionar explicação com vídeo na documentação do infoamazônia

**Comment by caio-ascava** [comment]
Realizada a validação com edição de traduções, através do perfil de admin e de um usuário criado, como editor e tradutor.
