### ISSUE TITLE
A lista de posts do Discovery não carrega mais outros itens

### ISSUE THREAD

**Issue by leopiccionia** [InfoAmazonia/jeo-plugin#436]
Se rolamos a listagem de posts para baixo, agora mais posts não aparecem mais. No lugar, ficam disponíveis apenas os posts mais recentes. Antes, novos posts apareciam à medida que se descia a lista de posts. O problema ocorre também no InfoSãoFrancisco.

**Comment by caio-ascava** [comment]
Concluída a atividade, que ao rolar tela para baixo o ícone de carregamento de novas notícias e localidades, apresentando em tom verde.
